- type: textarea
  attributes:
    label: Operating System
    description: What operating system are you using?
    placeholder: Example: macOS Big Sur
    value: operating system
  validations:
    required: true
- type: textarea
  attributes:
    label: .NET Core Version
    description: What version of .NET Coure are you using?
    placeholder: Example: macOS Big Sur
    value: netcore
  validations:
    required: true
- type: textarea
  attributes:
    label: IdentityServer
    description: What version of IdentityServer are you using?
    value: identityserver
  validations:
    required: true
